apiVersion: apps/v1
kind: Deployment
metadata:
  name: pneumonia-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pneumonia-app
  template:
    metadata:
      labels:
        app: pneumonia-app
    spec:
      containers:
      - name: pneumonia-app
        image: theanhhhhh/pneumonia-app:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "3Gi"
            cpu: "4"
          requests:
            memory: "1.5Gi"
            cpu: "1.5"
---
apiVersion: v1
kind: Service
metadata:
  name: pneumonia-service
spec:
  type: NodePort
  selector:
    app: pneumonia-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
